<a href="https://colab.research.google.com/github/ernxtorios/numpy-colab-notebooks/blob/main/NumPyFunctions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Functions

In [ ]:
import numpy as np

In [ ]:
a_arr = np.zeros(4)

a_arr

array([0., 0., 0., 0.])

In [ ]:
a_arr.ndim

1

In [ ]:
b_arr = np.zeros([2, 3])

b_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b_arr.ndim

2

In [ ]:
c_arr = np.ones(4)

c_arr

array([1., 1., 1., 1.])

In [ ]:
c_arr.ndim

1

In [ ]:
d_arr = np.ones([3, 4])

d_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
d_arr.ndim

2

In [ ]:
e_arr = np.eye(4)

e_arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
e_arr.ndim

2

In [ ]:
f_arr = np.diag([4, 5, 6, 7, 8])

f_arr

array([[4, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 8]])

In [ ]:
f_arr.ndim

2

In [ ]:
# np.random.randint(min, max, total)
g_arr = np.random.randint(1, 10, 5)

g_arr

array([6, 7, 3, 5, 7])

In [ ]:
# np.random.rand(total)
# Devuelve n números entre 0 y 1
h_arr = np.random.rand(5)

h_arr

array([0.74217082, 0.57923564, 0.82710579, 0.56608167, 0.61092894])

In [ ]:
i_arr = np.random.rand(3, 4)

i_arr

array([[0.00624021, 0.46771603, 0.26037544, 0.11570742],
       [0.30991458, 0.34755762, 0.12629553, 0.61408851],
       [0.92902406, 0.82590091, 0.66311671, 0.9615885 ]])

In [ ]:
i_arr.ndim

2

In [ ]:
j_arr = np.random.randn(5)

j_arr

array([ 1.25909863,  0.04391212,  0.25385387, -0.95740345, -1.16680543])

In [ ]:
lspace = np.linspace(1, 5, 4)

lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])