<a href="https://colab.research.google.com/github/ernxtorios/numpy-colab-notebooks/blob/main/NumPyArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Array

In [ ]:
import numpy as np

In [ ]:
a = [1, 2, 3, 4, 5]

a_arr = np.array(a)

a_arr

array([1, 2, 3, 4, 5])

In [ ]:
print(a_arr)

[1 2 3 4 5]


In [ ]:
a_arr.ndim

1

In [ ]:
a_arr.dtype

dtype('int64')

In [ ]:
a_arr.shape

(5,)

In [ ]:
a_arr.size

5

In [ ]:
b = [
    [1, 2, 3],
    [4, 5, 6]
]

b_arr = np.array(b)

b_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b_arr.ndim

2

In [ ]:
b_arr.dtype

dtype('int64')

In [ ]:
b_arr.shape

(2, 3)

In [ ]:
b_arr.size

6

In [ ]:
c_arr = np.arange(1, 15)

c_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
d_arr = np.arange(2, 19, 2)

d_arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])