<a href="https://colab.research.google.com/github/ernxtorios/numpy-colab-notebooks/blob/main/NumPyFunctionsArrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More Functions and Stacking on NumPy Arrays

## Functions of NumPy Arrays


In [ ]:
import numpy as np

a_arr = np.array([12, 3, 4, 61, 9, 10])

a_arr

array([12,  3,  4, 61,  9, 10])

In [ ]:
print(np.min(a_arr))

3


In [ ]:
print(np.max(a_arr))

61


In [ ]:
print(np.argmin(a_arr))

1


In [ ]:
print(np.argmax(a_arr))

3


In [ ]:
print(np.sqrt(a_arr))

[3.46410162 1.73205081 2.         7.81024968 3.         3.16227766]


In [ ]:
print(np.sin(a_arr))

[-0.53657292  0.14112001 -0.7568025  -0.96611777  0.41211849 -0.54402111]


In [ ]:
print(np.cos(a_arr))

[ 0.84385396 -0.9899925  -0.65364362 -0.25810164 -0.91113026 -0.83907153]


In [ ]:
np.random.seed(11)
matrix = np.random.randint(1, 21, 9).reshape(3, 3)
matrix

array([[17, 18, 14],
       [13,  2,  8],
       [19, 14, 17]])

In [ ]:
print(np.sum(matrix))

122


In [ ]:
print(np.min(matrix))

2


In [ ]:
print(np.max(matrix))

19


In [ ]:
print(np.min(matrix, axis=0)) # columnas
print(np.min(matrix, axis=1)) # filas

[13  2  8]
[14  2 14]


In [ ]:
print(np.max(matrix, axis=0)) # columnas
print(np.max(matrix, axis=1)) # filas

[19 18 17]
[18 13 19]


In [ ]:
matrix

array([[17, 18, 14],
       [13,  2,  8],
       [19, 14, 17]])

In [ ]:
print(np.sum(matrix, axis=0)) # columnas
print(np.sum(matrix, axis=1)) # filas

[49 34 39]
[49 23 50]


In [ ]:
np.cumsum(matrix)

array([ 17,  35,  49,  62,  64,  72,  91, 105, 122])

In [ ]:
matrix

array([[17, 18, 14],
       [13,  2,  8],
       [19, 14, 17]])

In [ ]:
print(np.cumsum(matrix, axis=0)) # columnas
print(np.cumsum(matrix, axis=1)) # filas

[[17 18 14]
 [30 20 22]
 [49 34 39]]
[[17 35 49]
 [13 15 23]
 [19 33 50]]


## Suffle and Unique

In [ ]:
b_arr = np.random.randint(1, 21, 10)

b_arr

array([ 1, 14, 13,  5,  3, 13,  2, 11,  6,  8])

In [ ]:
np.random.shuffle(b_arr)

b_arr

array([ 6,  3, 13,  5, 13, 11,  1, 14,  8,  2])

In [ ]:
c_arr = np.array([10, 20, 30, 40, 10, 20, 30, 50])

print(c_arr)
print(c_arr.size)

[10 20 30 40 10 20 30 50]
8


In [ ]:
np.unique(c_arr)

array([10, 20, 30, 40, 50])

In [ ]:
np.unique(c_arr).size

5

In [ ]:
np.unique(c_arr, return_index=True)

(array([10, 20, 30, 40, 50]), array([0, 1, 2, 3, 7]))

In [ ]:
np.unique(c_arr, return_index=True, return_counts=True)

(array([10, 20, 30, 40, 50]), array([0, 1, 2, 3, 7]), array([2, 2, 2, 1, 1]))

## Stacking

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [ ]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.random.seed(111)

a1 = np.random.randint(1, 21, 9).reshape(3, 3)
b1 = np.random.randint(21, 41, 9).reshape(3, 3)

print(a1)
print(b1)

[[13 20 10]
 [ 3 19  9]
 [ 8  8 13]]
[[31 22 37]
 [35 23 29]
 [26 33 27]]


In [ ]:
np.hstack((a1, b1))

array([[13, 20, 10, 31, 22, 37],
       [ 3, 19,  9, 35, 23, 29],
       [ 8,  8, 13, 26, 33, 27]])

In [ ]:
np.vstack((a1, b1))

array([[13, 20, 10],
       [ 3, 19,  9],
       [ 8,  8, 13],
       [31, 22, 37],
       [35, 23, 29],
       [26, 33, 27]])