<a href="https://colab.research.google.com/github/ernxtorios/numpy-colab-notebooks/blob/main/NumPySlicingViewCopyConditionalSelectionOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Slicing, View, Copy, Conditional Selection, Operations on Numpy Arrays

## Slicing

In [ ]:
import numpy as np

In [ ]:
np.random.seed(111)
a_arr = np.random.randint(1, 500, 30).reshape(6, 5)

a_arr

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [ ]:
# 4 primeras filas y 5 columnas
a_arr[:4, :]

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285]])

In [ ]:
a_arr[2:4, 1:4]

array([[456, 442,   8],
       [450, 369, 217]])

## View and Copy

In [ ]:
b_arr = np.arange(1, 16)
b_arr_view = b_arr[:].view()

print(b_arr)
print(b_arr_view)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
b_arr_view[3:6] = 0

print(b_arr)
print(b_arr_view)

[ 1  2  3  0  0  0  7  8  9 10 11 12 13 14 15]
[ 1  2  3  0  0  0  7  8  9 10 11 12 13 14 15]


In [ ]:
c_arr = np.arange(1, 16)
c_arr_copy = c_arr[:].copy()

print(c_arr)
print(c_arr_copy)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
c_arr_copy[3:6] = 0

print(c_arr)
print(c_arr_copy)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  2  3  0  0  0  7  8  9 10 11 12 13 14 15]


## Conditional Selection

In [ ]:
d_arr = np.arange(1, 16)

d_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
d_arr > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
d_arr[d_arr > 10]

array([11, 12, 13, 14, 15])

In [ ]:
print(d_arr)

print(d_arr[d_arr % 2 == 0])

print(d_arr[d_arr % 2 != 0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14]
[ 1  3  5  7  9 11 13 15]


## Mathematical Operations

In [ ]:
e_arr = np.arange(1, 5)

e_arr

array([1, 2, 3, 4])

In [ ]:
e_arr + 2

array([3, 4, 5, 6])

In [ ]:
e_arr * 2

array([2, 4, 6, 8])

In [ ]:
e_arr ** 2

array([ 1,  4,  9, 16])

In [ ]:
f_arr = np.arange(1, 5).reshape(2, 2)
g_arr = np.arange(5, 9).reshape(2, 2)

print(f_arr)
print(g_arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
f_arr + g_arr

array([[ 6,  8],
       [10, 12]])

In [ ]:
f_arr - g_arr

array([[-4, -4],
       [-4, -4]])

In [ ]:
f_arr * g_arr

array([[ 5, 12],
       [21, 32]])

In [ ]:
f_arr / g_arr

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
f_arr.dot(g_arr)

array([[19, 22],
       [43, 50]])