<a href="https://colab.research.google.com/github/ernxtorios/numpy-colab-notebooks/blob/main/NumPyReshapeSeedArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reshape

In [ ]:
import numpy as np

In [ ]:
a_arr = np.random.randint(1, 50, 12)

a_arr

array([ 6, 41, 17, 48, 46, 42, 26, 40, 31, 19, 25, 48])

In [ ]:
b_arr = a_arr.reshape(2, 6)

b_arr

array([[ 6, 41, 17, 48, 46, 42],
       [26, 40, 31, 19, 25, 48]])

In [ ]:
c_arr = b_arr.reshape(12)

c_arr

array([ 6, 41, 17, 48, 46, 42, 26, 40, 31, 19, 25, 48])

In [ ]:
d_arr = a_arr.reshape(3, -1)

d_arr

array([[ 6, 41, 17, 48],
       [46, 42, 26, 40],
       [31, 19, 25, 48]])

In [ ]:
e_arr = a_arr.reshape(-1, 4)

e_arr

array([[ 6, 41, 17, 48],
       [46, 42, 26, 40],
       [31, 19, 25, 48]])

In [ ]:
np.random.seed(12)

f_arr = np.random.randint(1, 50, 10)

f_arr

array([12, 28,  7,  3,  4,  4, 13, 49, 23,  6])

## Crea una matriz 1d a partir de la entrada del usuario

In [ ]:
lista = []
tamano = int(input("Ingrese el tamaño: "))
for i in range(tamano):
  valor = int(input("Ingrese un número: "))
  lista.append(valor)

g_arr = np.array(lista)

g_arr

Ingrese el tamaño: 5
Ingrese un número: 5
Ingrese un número: 2
Ingrese un número: 56
Ingrese un número: 89
Ingrese un número: 12


array([ 5,  2, 56, 89, 12])

## Matriz 2D tomando la entrada del usuario

In [ ]:
matriz = []
filas = int(input("Ingrese el número de filas: "))
columnas = int(input("Ingrese el número de columnas: "))

for i in range(filas):
  lista = []
  for i in range(columnas):
    valor = int(input("Ingrese un número: "))
    lista.append(valor)
  matriz.append(lista)

h_arr = np.array(matriz)

h_arr

Ingrese el número de filas: 2
Ingrese el número de columnas: 2
Ingrese un número: 2
Ingrese un número: 3
Ingrese un número: 1
Ingrese un número: 3


array([[2, 3],
       [1, 3]])